site_name: open-UST
site_url: https://morganjroberts.github.io/open-UST/
repo_url: https://github.com/morganjroberts/open-UST

# MAKE SURE ALL FILES FOLLOW HYPENATED CONVENTION

nav:
    - Home: index.md
    # - Background: background.md
    - Contact: contact.md
    - UST Background: background.md
    - Bill of Materials: bill-of-materials.md
    - Manufacture Preparation: 
        - Custom Tooling Manufacture: custom-tooling-manufacture.md
        - Offset Calibration for 3D-printed Parts: offset-calibration.md   
    - Transducer Manufacture:
        - PZT Element Preparation: pzt-element-preparation.md
        - Matching Layer Deposition: matching-layer-deposition.md
        - PZT Element Alignment: pzt-element-alignment.md
        - PCB-Housing Assembly: pcb-housing-assembly.md
        - Rear Electrode Connection: rear-electrode-connection.md
        - Backing Layer Casting: backing-layer-casting.md
        - Front Electrode Connection: front-electrode-connection.md      
        - Cable Preparation: cable-preparation.md
        - Strain Relief Clip Manufacture: strain-relief-clip-manufacture.md
        - Cable Installation: cable-installation.md
        - Electromagnetic Shielding: electromagnetic-shielding.md
        - Install Mounting Nuts: install-mounting-nuts.md
        - Rigid Coating: rigid-coating.md
        - Acoustic Coating: acoustic-coating.md
        - Finishing: finishing.md 
    - Additional Manufacture:
        - Plug Assembly: plug-assembly.md       
        - 2D Ring Array Mounting Plate: 2D-ring-array-mounting-plate.md
    - Impedance Matching:
        - Impedance Measurement: impedance-measurement.md
        - Impedance Matching Circuit: impedance-matching-circuit.md

extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - mdx_math

theme: 
    name: readthedocs
    logo: img/open-UST_logo.svg
