site_name: open-UST
site_url: https://morganjroberts.github.io/open-UST/
repo_url: https://github.com/morganjroberts/open-UST

# MAKE SURE ALL FILES FOLLOW HYPENATED CONVENTION

nav:
    - Home: index.md
    # - Background: background.md
    - Contact: contact.md
    - UST Background: background.md
    - Bill of Materials: bill-of-materials.md
    - Manufacturing Documentation:
        # - User Workflow Overview: user_workflow_overview.md
        # - Custom Tooling Manufacture: custom-tooling-manufacture.md
        - PZT Element Preparation: pzt-element-preparation.md
        - Matching Layer Deposition: matching-layer-deposition.md
        - PZT Element Alignment: pzt-element-alignment.md
        # - Interconnect PCB Soldering: interconnect_pcb_soldering.md
        # - Housing - PCB bonding: housing_-_pcb_bonding.md
        - Rear Electrode Connection: rear-electrode-connection.md
        - Backing Layer Casting: backing-layer-casting.md
        - Front Electrode Connection: front-electrode-connection.md      
        # - Impedance Measurement: impedance_measurement.md
        - Cable Preparation: cable-preparation.md
        - Strain Relief Clip Manufacture: strain-relief-clip-manufacture.md
        - Cable Installation: cable-installation.md
        - Electromagnetic Shielding: electromagnetic-shielding.md
        # - Install Mounting Points: install_mounting_points.md
        # - Rigid Coating Casting: rigid_coating_casting.md
        # - Acoustic Coating Casting: acoustic_coating_casting.md
        # - Bend Relief Installation: bend_relief_installation.md 
        # - Plug Backshell Fabrication: plug_backshell_fabrication.md
        # - Electrical Impedance Matching: electrical_impedance_matching.md
        # - Modular Array Assembly: array_assembly.md

extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - mdx_math

theme: 
    name: readthedocs
    logo: img/open-UST_logo.svg
